### ISSUE TITLE
Update to 1.4.22

### ISSUE THREAD

**Issue by caffodian** [PolicyStat/django#4]
refs https://github.com/PolicyStat/PolicyStat/issues/2169

**Comment by caffodian** [comment]
approach:  pull in upstream/stable/1.4.x into this repo's /stable/1.4.x

then put that into the forked 1.4.x branch, run tests and make sure the regression tests in particular pass

**Comment by kylegibson** [comment]
Would it be worth it to try updating our requirements to use bare 1.4.22 and see if any tests fail?

**Comment by caffodian** [comment]
Sure, I'll try that first.  I've taken care of the django merge and am running tests locally.

The thing I am concerned about is that I don't currently have the context to know what originally broke and whether or not there is coverage for it.  But I can dig. :)

**Comment by caffodian** [comment]
some notes so I don't need to keep re-finding things 

https://github.com/PolicyStat/django/compare/1.4.x-patched...PolicyStat:issue_4 the diff between our patched 1.4.21 and patched 1.4.22, for my sanity 

a failing test case on both 1.4.22 and unpatched 1.4.22, but not on patched 1.4.21

http://jenkins.pstattest.com/job/pstat_ticket_unittest_3/6469/testReport/pstat.document_import.holds.test_views/PermissionTestCase/test_guest_user_displays_login_required_on_list_page/

http://jenkins.pstattest.com/job/pstat_ticket_unittest_3/6796/testReport/pstat.document_import.holds.test_views/PermissionTestCase/test_guest_user_displays_login_required_on_list_page/

**Comment by caffodian** [comment]
Ah.  TIL guest is actually a type of login, and `login_as_guest` doesn't appear to actually do so under either of the 1.4.22 branches....the adventure continues

**Comment by caffodian** [comment]
closed via 987632fa96bfa65f00e7a4d2283b54eec7ef720c in https://github.com/PolicyStat/django/tree/v1.4.22
